language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules  
script:
  - yarn build
deploy:
  email: arojunior@gmail.com
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
env:
  - CI=false